<?php
require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/src/Radius/RadiusDatabase.php';
require_once __DIR__ . '/src/Auth/AuthService.php';

$config = require __DIR__ . '/config/config.php';
$db = new RadiusDatabase($config['database']);
$pdo = $db->getPdo();
$auth = new AuthService($pdo);

// Find superadmin
$stmt = $pdo->query("SELECT id FROM users WHERE role = 'superadmin' LIMIT 1");
$superadminId = $stmt->fetchColumn() ?: 1;

// Insert a test notification
$stmt = $pdo->prepare("INSERT INTO system_notifications (title, message, type, created_by) VALUES (?, ?, 'info', ?)");
$stmt->execute(['Test Notification', 'This is a test notification generated by the system.', $superadminId]);

echo "Test notification inserted successfully. ID: " . $pdo->lastInsertId() . "\n";
