-- Migration 051: Password reset tokens + Email template storage
-- Date: 2026-03-04

-- 1. Add password reset columns to users table
ALTER TABLE users
    ADD COLUMN password_reset_token VARCHAR(64) DEFAULT NULL,
    ADD COLUMN password_reset_expires_at TIMESTAMP NULL DEFAULT NULL;

-- 2. Index for fast token lookups
ALTER TABLE users
    ADD INDEX idx_password_reset_token (password_reset_token);

-- 3. Email templates stored in global_settings
INSERT IGNORE INTO global_settings (setting_key, setting_value, description) VALUES
('email_template_verification_subject', '{{app_name}} - Vérifiez votre adresse email', 'Sujet du mail de vérification'),
('email_template_verification_body', '<!DOCTYPE html>\n<html>\n<head><meta charset=\"UTF-8\"></head>\n<body style=\"margin:0;padding:0;background-color:#f3f4f6;font-family:Arial,Helvetica,sans-serif;\">\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f3f4f6;padding:40px 0;\">\n<tr><td align=\"center\">\n<table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 6px rgba(0,0,0,0.1);\">\n    <tr><td style=\"background: linear-gradient(135deg, #2563eb, #1d4ed8); padding: 30px; text-align: center;\"><h1 style=\"color:#ffffff;margin:0;font-size:24px;\">{{app_name}}</h1></td></tr>\n    <tr><td style=\"padding:30px;\">\n        <h2 style=\"color:#1f2937;margin:0 0 15px 0;font-size:20px;\">Vérification de votre adresse email</h2>\n        <p style=\"color:#4b5563;font-size:15px;line-height:1.6;\">Bonjour <strong>{{username}}</strong>,<br><br>Merci de vous être inscrit sur <strong>{{app_name}}</strong>. Pour activer votre compte, veuillez cliquer sur le bouton ci-dessous :</p>\n        <div style=\"text-align:center;margin:30px 0;\"><a href=\"{{link}}\" style=\"display:inline-block;background-color:#2563eb;color:#ffffff;text-decoration:none;padding:14px 32px;border-radius:8px;font-size:16px;font-weight:bold;\">Vérifier mon email</a></div>\n        <p style=\"color:#6b7280;font-size:13px;line-height:1.5;\">Si le bouton ne fonctionne pas, copiez ce lien :<br><a href=\"{{link}}\" style=\"color:#2563eb;word-break:break-all;\">{{link}}</a></p>\n        <p style=\"color:#9ca3af;font-size:12px;margin-top:20px;\">Ce lien expire dans {{expiry_hours}} heures.</p>\n    </td></tr>\n    <tr><td style=\"background-color:#f9fafb;padding:20px;text-align:center;border-top:1px solid #e5e7eb;\"><p style=\"color:#9ca3af;font-size:12px;margin:0;\">&copy; {{app_name}}</p></td></tr>\n</table>\n</td></tr></table>\n</body></html>', 'Corps HTML du mail de vérification'),
('email_template_reset_subject', '{{app_name}} - Réinitialisez votre mot de passe', 'Sujet du mail de réinitialisation'),
('email_template_reset_body', '<!DOCTYPE html>\n<html>\n<head><meta charset=\"UTF-8\"></head>\n<body style=\"margin:0;padding:0;background-color:#f3f4f6;font-family:Arial,Helvetica,sans-serif;\">\n<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#f3f4f6;padding:40px 0;\">\n<tr><td align=\"center\">\n<table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 6px rgba(0,0,0,0.1);\">\n    <tr><td style=\"background: linear-gradient(135deg, #dc2626, #b91c1c); padding: 30px; text-align: center;\"><h1 style=\"color:#ffffff;margin:0;font-size:24px;\">{{app_name}}</h1></td></tr>\n    <tr><td style=\"padding:30px;\">\n        <h2 style=\"color:#1f2937;margin:0 0 15px 0;font-size:20px;\">Réinitialisation de votre mot de passe</h2>\n        <p style=\"color:#4b5563;font-size:15px;line-height:1.6;\">Bonjour <strong>{{username}}</strong>,<br><br>Vous avez demandé la réinitialisation de votre mot de passe sur <strong>{{app_name}}</strong>. Cliquez sur le bouton ci-dessous :</p>\n        <div style=\"text-align:center;margin:30px 0;\"><a href=\"{{link}}\" style=\"display:inline-block;background-color:#dc2626;color:#ffffff;text-decoration:none;padding:14px 32px;border-radius:8px;font-size:16px;font-weight:bold;\">Réinitialiser mon mot de passe</a></div>\n        <p style=\"color:#6b7280;font-size:13px;line-height:1.5;\">Si le bouton ne fonctionne pas, copiez ce lien :<br><a href=\"{{link}}\" style=\"color:#dc2626;word-break:break-all;\">{{link}}</a></p>\n        <p style=\"color:#9ca3af;font-size:12px;margin-top:20px;\">Ce lien expire dans {{expiry_hours}} heure(s).</p>\n    </td></tr>\n    <tr><td style=\"background-color:#f9fafb;padding:20px;text-align:center;border-top:1px solid #e5e7eb;\"><p style=\"color:#9ca3af;font-size:12px;margin:0;\">&copy; {{app_name}}</p></td></tr>\n</table>\n</td></tr></table>\n</body></html>', 'Corps HTML du mail de réinitialisation'),
('password_reset_expiry_hours', '1', 'Durée de validité du lien de réinitialisation (heures)');
